name = "multiplayer-car-game-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# KV namespace for chunk caching
[[kv_namespaces]]
binding = "roadrush"
id = "b37db24f53c54d07a17864b49792176f"
preview_id = "b37db24f53c54d07a17864b49792176f"

# Durable Objects for WebSocket rooms
[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]

# Secrets (set via: wrangler secret put SECRET_NAME)
FIREBASE_API_KEY = "2COtn0c6LxPFuSTzvT00aUJLEia37h3CMpQrW6Ig"
FIREBASE_URL = "https://roadrush-b3ece-default-rtdb.asia-southeast1.firebasedatabase.app"
FIREBASE_PROJECT_ID = "roadrush"
